### ISSUE TITLE
License

### ISSUE THREAD

**Issue by kkloppqq** [beyondbeneath/bezier-curved-edges-networkx#2]
Hi,

I really like your bezier tool. They make network graphs look significantly nicer. Would you be open to adding a permissive license?

**Comment by beyondbeneath** [comment]
Sorry for the delayed reply @kkloppqq - I usually do add a license, but clearly forgot this time :) I can do so - out of interest, what exactly did you plan on doing with this?

**Comment by kkloppqq2** [comment]
Hey, sorry this fell off my radar for a while. I'm mostly just interested in using this code to generate some nice images for clients. Hypothetically I could imagine wrapping it up into dash app and providing it to others closed source, so MIT may be preferred. But I'd be thrilled with anything that gave me the right to use it for commercial purposes in general.

Thanks!

**Comment by beyondbeneath** [comment]
Done and thanks for the reminder too - closing this issue!
